### ISSUE TITLE
Incompatible with Apotheosis 7.4.0 on 1.20.1

### ISSUE THREAD

**Issue by CelestialAbyss** [elseytd/LootBeams#46]
Just wanted to let you know ahead of time.

- Forge `47.3.1`
- Apotheosis `7.4.0`
- Loot Beams `1.2.5`

Relevant logs can be seen here: https://gist.github.com/CelestialAbyss/6da350740cfa284d575ed3a0ef4697bf

Normally a crash would occur but Neruina is safely handling it in the meantime.

**Comment by briarss** [comment]
Yeah, i know, i'm in the middle of a 1.21 rewrite so ill get to this when i have time - i get told of breaking apoth changes early bc i'm friendly w the dev but i still just dont have time lol

**Comment by ReeCodes** [comment]
Alright. I can attest; experiencing the same.

**Comment by cutekitticat** [comment]
Same for me !

**Comment by briarss** [comment]
This is known about, it will happen for anyone on the latest apoth ver, i've just not had time to update.
