### ISSUE TITLE
Lodestone Compass disappears when dropped when installed with Improved Lodestones

### ISSUE THREAD

**Issue by Cephelo** [elseytd/LootBeams#49]
Disclaimer: Sinytra Connector is involved.  That being said, the stacktraces do specifically mention both mods.

Mods installed:
[Improved Lodestones 1.0](https://www.curseforge.com/minecraft/mc-mods/improved-lodestones/files/5029703)
[Forgified Fabric API 0.92.2-1.11.8](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api/files/5387432)
[Sinytra Connector (beta 45)](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector/files/5605667)
[Loot Beams 1.2.6](https://www.curseforge.com/minecraft/mc-mods/loot-beams/files/5548970)
Forge 47.3.0

Behavior: When dropping a lodestone compass, the item vanishes entirely.

Stacktrace:
[lootbeams-imp_lodes-stacktrace.txt](https://github.com/user-attachments/files/16596724/lootbeams-imp_lodes-stacktrace.txt)

No crashlog was generated.
Please let me know if you need anything else.
Sister issue: Aegrithas/ImprovedLodestones#3

**Comment by briarss** [comment]
This is an issue with Improved Lodestones, loot beams is only mentioned because it calls the tooltip method when rendering tooltips in world.

**Comment by Cephelo** [comment]
The issue does not occur if Loot Beams is not installed, and only the other three mods are.  If Loot Beams isn't installed, the Lodestone Compass drops normally.

**Comment by Aegrithas** [comment]
I can verify that this is an Improved Lodestones problem, you can close this issue.

**Comment by Cephelo** [comment]
Gotcha, thanks for looking into it!
